### ISSUE TITLE
Change organisation to identify community nature

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-Hive/website#140]
ACCESS-NRI wants the community to be able to use the same organisation to host orphaned documentation. 

As a user having the GitHub organisation named the same as the documentation hub repository (ACCESS-Hive) does not give the impression that the organisation can be used by the community for this purpose.

The suggestion was to change the name of the organisation from ACCESS-Hive to ACCESS-Community. This is not possible, as github.com/ACCESS-Community already exists. 

Other options:

- `ACCESS_Community`
- `ACCESS-Public`
- `ACCESS-Common` 
- `ACCESS-Collective`

**Comment by ccarouge** [comment]
I like ACCESS-Collective. Other idea: ACCESS-Hub. We changed the name because we thought that would solve the indexing with search engines but it hasn't so we could go back to it.
